# Generated by Django 3.2 on 2021-06-19 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='creates_at',
            new_name='created_at',
        ),
    ]
